version: "3.9"
services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend_image
    container_name: backend_container
    ports:
      - "8080:8080"
      - "5432:5432"